In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [4]:
dataset=pd.read_csv('Malware dataset.csv')
dataset2=dataset.copy()
dataset2=dataset.drop(['classification'],axis=1)

X=dataset2.iloc[:,1:].values
y=dataset.iloc[:,2].values

In [6]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
y=le.fit_transform(y)

In [7]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.25,random_state=0)

In [8]:
print(X_train)

[[  606 12288     0 ...    10     0     0]
 [  228 28672     0 ...     0     0     0]
 [  382  4096     0 ...     1     0     0]
 ...
 [  613 12288     0 ...    11     0     0]
 [  567  4096     0 ...     2     0     0]
 [  268     0     0 ...     0     0     0]]


In [9]:
print(y_train)

[0 1 0 ... 0 0 1]


In [10]:
print(X_test)

[[    582       0       0 ...       8       0       0]
 [    498       0       0 ...       0       0       0]
 [    227 1028096       0 ...       4       0       0]
 ...
 [    585    4096       0 ...       0       0       0]
 [    519       0       0 ...       7       0       0]
 [    831       0       0 ...       0       0       0]]


In [12]:
print(y_test)

[1 0 0 ... 1 0 0]


In [13]:
from sklearn.naive_bayes import GaussianNB
model = GaussianNB()
model.fit(X_train,y_train)

GaussianNB()

In [15]:
y_pred=model.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1))

[[1 1]
 [1 0]
 [0 0]
 ...
 [1 1]
 [0 0]
 [1 0]]


In [16]:
from sklearn.metrics import confusion_matrix,accuracy_score
cm=confusion_matrix(y_test,y_pred)
print(cm)
accuracy_score(y_test,y_pred)

[[ 4972  7556]
 [ 1939 10533]]


0.6202

In [17]:
from sklearn.metrics import accuracy_score,precision_score,recall_score
print("Accuracy = ",accuracy_score(y_test,y_pred))
print("Precision = ",precision_score(y_test,y_pred))
print("Recall = ",recall_score(y_test,y_pred))

Accuracy =  0.6202
Precision =  0.5822875780861297
Recall =  0.8445317511225144
